version: '3'
services:
  mongo:
    image: mongo:3.6
    volumes:
       - /data/mongodb:/var/data/db
  versionspout:
    image: sapien99/versionspout:0.9.0
    volumes:
       - versionspout/mounts:/opt/app/mounts
    environment:
      - CONFIG=/opt/app/mounts/configmaps/config.yaml
      - PASSWORDS=/opt/app/mounts/secrets/creds.yaml
      - ASSETS=/opt/app/mounts/assets
